### PR TITLE
Up gem version to 3.3.9

### PR DESCRIPTION
**Pull request by ilyaerin**

### CODE REVIEW

**Review by em-gazelle — CHANGES_REQUESTED** [review]
@ilyaerin https://github.com/HireFrederick/booker_ruby/pull/25 see comments on this PR - some of this is duplicated from the booker_ruby_internal gem (same base url of v5/internal/locations)

**Comment by ilyaerin** [comment]
@em-gazelle there're few differences between these repositories:
- This is a public repository, `booker_ruby_internal` - is a private.
- `booker_ruby_internal` is based on this repository.
- All models and basic methods are set up in this public repo.

My changes need to add a new model and the request that is available in a public Booker documentation. That is why I suppose current repository is better appropriate for this code. Also, as `booker_ruby_internal` is based on this repo, we should update this repo first and after that update/merge and our private repository. I suppose we can update `booker_ruby_internal` after this release.

**Review by mstahl — APPROVED** [review]

**Review by mstahl — CHANGES_REQUESTED** [review]
@ilyaerin Emma noticed the PR she linked to adds internal routes to this gem, which probably wasn't what was intended. Those should go in the internal gem instead.

**Comment by ilyaerin** [comment]
@em-gazelle @mstahl thanks. I'm going to move these code to the internal gem

**Comment by ilyaerin** [comment]
@em-gazelle @mstahl Reverted this API endpoint in the current repo: https://github.com/HireFrederick/booker_ruby/pull/27 Also, I've moved the same changes to the internal repository.

**Review by mstahl — APPROVED** [review]

**Comment by em-gazelle** [comment]
Let's just bump the gem version [here](https://github.com/HireFrederick/booker_ruby/pull/27) and close this PR

**Pull request closed without merging**
